include($$PWD/buttonedit/buttonedit.pri)
include($$PWD/gaugeplane/gaugeplane.pri)
include($$PWD/lightbutton/lightbutton.pri)
include($$PWD/progressbarcolor/progressbarcolor.pri)
include($$PWD/radiobuttons/radiobuttons.pri)
include($$PWD/radiusprogressbar/radiusprogressbar.pri)
include($$PWD/buttongroup/buttongroup.pri)
include($$PWD/clock/clock.pri)
include($$PWD/waveform/waveform.pri)
include($$PWD/progressbarwater/progressbarwater.pri)

